<?php 
#OBTEM O CAMINHO DO ARQUIVO .PHP QUE ESTÁ A SER EXECUTADO
echo $_SERVER['PHP_SELF']."<br>";

#OBTEM O NOME DO SERVIDOR
echo $_SERVER['SERVER_NAME']."<br>";

#OBTEM O NOME DO DOMÍNIO DO SERVIDOR ex:google.com ou local host
echo $_SERVER['HTTP_HOST']."<br>";

#OBTEM A URL QUE CHAMOU A PAGINA ATUAL.
echo $_SERVER['HTTP_REFERER']."<br>";

#OBTEM INFORMAÇÕES SOBRE O AGENTE(normalmente o navegador) QUE ESTÁ SENDO USADO, ASSIM COMO O SO
echo $_SERVER['HTTP_USER_AGENT']."<br>";

#OBTEM O CAMINHO DO ARQUIVO .PHP QUE ESTÁ A SER EXECUTADO
echo $_SERVER['SCRIPT_NAME']."<br>";

#OBTEM O NOME DA PORTA QUE ESTÁ A SER USADA PELO USUARIO PARA SE COMUNICAR COM O SERVIDOR
echo $_SERVER['REMOTE_PORT']."<br>";

# OBTEM O METODO DE REQUISIÇÃO.
echo $_SERVER["REQUEST_METHOD"];
?>